name: NuGet_Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    env:
      NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_TOKEN}}

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and generate uCrop
      run: |
        cd src/uCrop/yalantis.ucrop.xamarin
        dotnet restore
        msbuild yalantis.ucrop.xamarin.csproj /p:Configuration=Release
        nuget pack yalantis.ucrop.xamarin.nuspec
        nuget push "*.nupkg" -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json

    - name: Build and generate uCrop.Native
      run: |
        cd src/uCrop.Native/yalantis.ucrop.native.xamarin
        dotnet restore
        msbuild yalantis.ucrop.native.xamarin.csproj /p:Configuration=Release
        nuget pack yalantis.ucrop.native.xamarin.nuspec
        nuget push "*.nupkg" -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
