name: NuGet_Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_TOKEN}}  
    - name: Build and generate uCrop
      run: |
        cd src/uCrop/yalantis.ucrop.xamarin
        nuget restore
        msbuild yalantis.ucrop.xamarin.csproj -t:pack /p:Configuration=Release

    - name: Build and generate uCrop.Native
      run: |
        cd src/uCrop.Native/yalantis.ucrop.native.xamarin
        nuget restore
        msbuild yalantis.ucrop.native.xamarin.csproj -t:pack /p:Configuration=Release
